version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: choco install --limit-output -y 7zip
- ps: choco install --limit-output -y winrar
build_script:
- ps: ./Test.ps1
artifacts:
- path: Results/*