version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: choco install --limit-output -y 7zip
- ps: choco install --limit-output -y winrar
build_script:
- ps: ./Test.ps1
after_build:
    - ps: Get-ChildItem .\Results\* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
    - path: Results